<a href="https://colab.research.google.com/github/Alaa-f-Abdalaal/ITI-TASKS/blob/main/Python_Numpy_Exercises_with_hints.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python NumPy Exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` and print the numpy version and the configuration (★☆☆)

`Hint: import … as` and `np.__version__, np.show_config)`

In [6]:
import numpy as np
print(np.__version__)
print(np.show_config)

2.0.2
<function show at 0x7fe8a68e3420>


#### 2. Convert a list of numeric value into a one-dimensional NumPy array (★☆☆)
`💡 hint: numpy.array`

In [7]:
list=[1,2,3,4,5]
np.array(list)

array([1, 2, 3, 4, 5])

#### 3. Create a null vector of size 9 (★☆☆)
`💡 hint: np.zeros`

In [8]:
null_vector = np.zeros(9)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)
`💡 hint: size, itemsize`

In [10]:
array=np.array([1,2,3,4,5])
print(array.size)
print(array.itemsize)

5
8


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
`💡hint: np.info`

In [11]:
np.info()

 info(object=None, maxwidth=76, output=None, toplevel='numpy')

Get help information for an array, function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is
    an `ndarray` instance, information about the array is printed.
    If `object` is a numpy object, its docstring is given. If it is
    a string, available modules are searched for matching objects.
    If None, information about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``None``, in which case ``sys.stdout`` will be used.
    The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> n

#### 6. Create a null vector of size 12 but the sixth value which is 1 (★☆☆)
`💡hint: array[12]`

In [15]:
arr = np.zeros(12)
arr[5] = 1
arr


array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 20 to 59 (★☆☆)
`💡hint: arange`

In [16]:
arr=np.arange(20,60)
print(arr)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]


#### 8. Reverse a vector (first element becomes last) (★☆☆)
`💡hint: array[::-1]`

In [17]:
arr=np.array([1,2,3,4,5])
arr[::-1]

array([5, 4, 3, 2, 1])

#### 9. Create a 3x3 matrix with values ranging from 12 to 20 (★☆☆)
`💡hint: reshape`

In [18]:
arr=np.arange(12,21).reshape(3,3)
print(arr)

[[12 13 14]
 [15 16 17]
 [18 19 20]]


#### 10. Find indices of non-zero elements from [3,7,0,0,9,0] (★☆☆)
`💡hint: np.nonzero`

In [19]:
arr=np.array([3,7,0,0,9,0])
np.nonzero(arr)

(array([0, 1, 4]),)

#### 11. Create a 4x4 identity matrix (★☆☆)
`💡hint: np.eye`

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### 12. Create a 2x2x2 array with random values (★☆☆)
`💡hint: np.random.random`

In [21]:
np.random.random((2,2,2))

array([[[0.79295543, 0.76122195],
        [0.0817759 , 0.91305317]],

       [[0.11473647, 0.62935721],
        [0.94251357, 0.98438805]]])

#### 13. Create a 9x9 array with random values and find the minimum and maximum values (★☆☆)
`💡hint: min, max`

In [28]:
arr = np.random.rand(9, 9)
min_val = arr.min()
max_val = arr.max()
print("Array:\n", arr)
print("Minimum value:", min_val)
print("Maximum value:", max_val)

Array:
 [[0.19170979 0.46076901 0.58615781 0.69334398 0.46225239 0.95919581
  0.47108409 0.53462963 0.63764701]
 [0.154065   0.89298633 0.70653103 0.41040944 0.93449971 0.13879819
  0.43463952 0.10418886 0.45057229]
 [0.62997698 0.07512742 0.66962437 0.50362401 0.59974166 0.70222771
  0.11248853 0.18081153 0.25022312]
 [0.48553826 0.34172376 0.17926481 0.66794732 0.84272553 0.92399092
  0.68272775 0.01787209 0.36869317]
 [0.18174663 0.65398757 0.51101952 0.78397235 0.9309323  0.82270729
  0.08222714 0.25615556 0.0115227 ]
 [0.61195718 0.03947692 0.85925681 0.40706508 0.47216042 0.78546576
  0.19780401 0.19936616 0.21736217]
 [0.07887916 0.1425265  0.28694805 0.26758195 0.81339391 0.8313536
  0.16222353 0.42383319 0.09229706]
 [0.62565912 0.67067445 0.80660152 0.57960285 0.57671332 0.21744583
  0.41559724 0.7303294  0.84653554]
 [0.95073931 0.90515917 0.02095608 0.02874896 0.86863405 0.84551227
  0.70237886 0.29324301 0.31718252]]
Minimum value: 0.011522696757125472
Maximum value: 0.959

#### 14. Create a random vector of size 20 and find the mean value (★☆☆)
`💡hint: mean`

In [29]:
np.random.random(20).mean()

np.float64(0.6630293228038431)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
`💡hint: array[1:-1, 1:-1]`

In [33]:
arr=np.ones((5,5))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
`💡hint: np.pad`

In [37]:
import numpy as np


arr = np.ones((3, 3))
print("Original array:\n", arr)


arr_with_border = np.pad(arr, pad_width=1)
print("\nArray with border:\n", arr_with_border)


Original array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array with border:
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```
`💡hint: NaN = not a number, inf = infinity`

In [ ]:
nan
False
False
nan
True
False

#### 18. Create a 6x6 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`💡hint: np.diag`

In [38]:
import numpy as np
values = np.array([1, 2, 3, 4, 5])
matrix = np.diag(values, k=-1)
print(matrix)


[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


#### 19. Create a 6x6 matrix and fill it with a checkerboard pattern (★☆☆)
`💡hint: array[::2]`

In [39]:
checkerboard = np.zeros((6, 6), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)


[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


#### 20. Consider a (8,9,10) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
`💡hint: np.unravel_index`

In [40]:
shape = (8, 9, 10)
index = np.unravel_index(100, shape)
print(index)


(np.int64(1), np.int64(1), np.int64(0))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
`💡hint: np.tile`

In [41]:
import numpy as np
pattern = np.array([[0, 1],
                    [1, 0]])
checkerboard = np.tile(pattern, (4, 4))
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 6x6 random matrix (★☆☆)
`💡hint: (x -mean)/std`

In [42]:
import numpy as np
Z = np.random.random((6, 6))
mean = np.mean(Z)
std = np.std(Z)
Z_normalized = (Z - mean) / std
print("Original Matrix:\n", Z)
print("\nNormalized Matrix:\n", Z_normalized)


Original Matrix:
 [[0.48054793 0.49638239 0.71618793 0.92965886 0.06665149 0.21141217]
 [0.30905255 0.7764908  0.12664872 0.48834138 0.05579544 0.2004368 ]
 [0.57919651 0.77317931 0.30524113 0.08234793 0.12410113 0.05215306]
 [0.08582078 0.62739404 0.64975652 0.26621526 0.50091919 0.20106674]
 [0.75032258 0.84268861 0.583545   0.0438301  0.36546025 0.46421732]
 [0.6046648  0.16130311 0.10089894 0.44117523 0.08170333 0.30804988]]

Normalized Matrix:
 [[ 0.36562915  0.42609664  1.26547409  2.08066134 -1.21492847 -0.6621269 ]
 [-0.28926491  1.4957543  -0.98581541  0.39539023 -1.25638477 -0.70403885]
 [ 0.74234118  1.48310863 -0.30381969 -1.15498803 -0.99554397 -1.27029401]
 [-1.14172619  0.92639441  1.01179063 -0.45284884  0.44342147 -0.70163329]
 [ 1.39582498  1.74854565  0.75894689 -1.30207714 -0.0738593   0.303267  ]
 [ 0.83959765 -0.85347975 -1.0841468   0.21527555 -1.1574496  -0.29309386]]


#### 23. find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. (★☆☆)

In [43]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
num_elements = arr.size
element_size = arr.itemsize
total_bytes = arr.nbytes

print("Number of elements:", num_elements)
print("Length of one element in bytes:", element_size)
print("Total bytes consumed:", total_bytes)


Number of elements: 6
Length of one element in bytes: 8
Total bytes consumed: 48


#### 24. Multiply a 6x3 matrix by a 3x4 matrix (real matrix product) (★☆☆)
`💡hint: np.dot` or `np.ones`

In [44]:
import numpy as np
A = np.ones((6, 3))
B = np.ones((3, 4))


result = np.dot(A, B)

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Result of A x B:\n", result)


Matrix A:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Matrix B:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Result of A x B:
 [[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
`💡hint: >, <`

In [45]:
import numpy as np


arr = np.arange(10)
print("Original array:", arr)


mask = (arr > 3) & (arr < 8)


arr[mask] *= -1

print("Modified array:", arr)


Original array: [0 1 2 3 4 5 6 7 8 9]
Modified array: [ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

#### 27. Write a Python program compare two arrays using numpy (★☆☆)
```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [46]:
import numpy as np


a = np.array([1, 2])
b = np.array([4, 5])


print("a > b")
print(a > b)


print("a >= b")
print(a >= b)


print("a < b")
print(a < b)


print("a <= b")
print(a <= b)


a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```
Consider an integer vector a
```python
a**a
a << a >> 2
a <- a
1j*a
a/1/1
a<a>a
```

In [ ]:
nan
array([ 1,  4, 27])
array([0, 2, 6])
array([0.+1.j, 0.+2.j, 0.+3.j])
array([1., 2., 3.])
array([False, False, False])



#### 29. How to round away from zero a float array ? (★☆☆)
`💡hint: np.uniform, np.copysign, np.ceil, np.abs, np.where`

In [47]:
import numpy as np
arr = np.random.uniform(-10, 10, 5)
print("Original:", arr)
rounded = np.copysign(np.ceil(np.abs(arr)), arr)
print("Rounded away from zero:", rounded)


Original: [ 5.95685699  9.35584557  6.35900697  1.80868109 -9.93622631]
Rounded away from zero: [  6.  10.   7.   2. -10.]


#### 30. How to find common values between two arrays? (★☆☆)
`💡hint: np.intersect1d`

In [48]:
import numpy as np


arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])


common_values = np.intersect1d(arr1, arr2)

print(common_values)


[3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
`💡hint: np.seterr, np.errstate`

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```
`💡hint: imaginary number`

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
`💡hint: np.datetime64, np.timedelta64`

#### 34. How to get all the dates corresponding to the month of January 2016? (★★☆)
`💡hint: np.arange(dtype=datetime64['D'])`

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
`💡hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=)`

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
`💡hint: %, np.floor, astype, np.trunc`

#### 37. Create a 3x3 matrix with row values ranging from 0 to 2 (★★☆)
`💡hint: np.arange`

#### 38. Consider a generator function that generates 9 integers and use it to build an array (★☆☆)
`💡hint: np.fromiter`

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
`💡hint: np.linspace`

#### 40. Create a random vector of size 10 and sort it (★★☆)
`💡hint: sort`

#### 41. How to sum a small array faster than np.sum? (★★☆)
`💡hint: np.add.reduce`

#### 42. Consider two random array A and B, check if they are equal (★★☆)
`💡hint: np.allclose, np.array_equal`

#### 43. Make an array immutable (read-only) (★★☆)
`💡hint: flags.writeable`

#### 44. Consider a random 5x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
`💡hint: np.sqrt, np.arctan2`

#### 45. Create random vector of size 5 and replace the maximum value by 0 (★★☆)
`💡hint: argmax`

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
`💡hint: np.meshgrid`

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
`💡hint: np.subtract.outer`

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
`💡hint: np.iinfo, np.finfo, eps`

#### 49. How to print all the values of an array? (★★☆)
`💡hint: np.set_printoptions`

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
`💡hint: argmin`

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
`💡hint: dtype`

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
`💡hint: np.atleast_2d, T, np.sqrt`

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
`💡hint: view and [:] =`

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```
`💡hint: np.genfromtxt`

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
`💡hint: np.ndenumerate, np.ndindex`

#### 56. Generate a generic 2D Gaussian-like array (★★☆)
`💡hint: np.meshgrid, np.exp`

#### 57. How to randomly place e elements in a 2D array? (★★☆)
`💡hint: np.put, np.random.choice`

#### 58. Subtract the mean of each row of a matrix (★★☆)
`💡hint: mean(axis=,keepdims=)`

#### 59. How to sort an array by the nth column? (★★☆)
`💡hint: argsort`

#### 60. How to tell if a given 2D array has null columns? (★★☆)
`💡hint: any, ~`

#### 61. Find the nearest value from a given value in an array (★★☆)
`💡hint: np.abs, argmin, flat`

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
`💡

#### 63. Create an array class that has a name attribute (★★☆)
`💡hint: class method`

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
`💡hint: np.bincount | np.add.at`

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
`💡hint: np.bincount`

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
`💡hint: np.unique`

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
`💡hint: sum(axis=(-2,-1))`

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)
`💡hint: np.bincount`

#### 69. How to get the diagonal of a dot product? (★★★)
`💡hint: np.diag`

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
`💡hint: array[::4]`

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
`💡hint: array[:, :, None]`

#### 72. How to swap two rows of an array? (★★★)
`💡hint: array[[]] = array[[]]`

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)
`💡hint: repeat, np.roll, np.sort, view, np.unique`

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
`💡hint: np.repeat`

#### 75. How to compute averages using a sliding window over an array? (★★★)
`💡hint: np.cumsum`

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
`💡hint: from numpy.lib import stride_tricks`

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
`💡hint: np.logical_not, np.negative`

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)
`💡hint: minimum maximum`

#### 81. Consider an array a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
`💡hint: stride_tricks.as_strided`

#### 82. Compute a matrix rank (★★★)
`💡hint: np.linalg.svd`

#### 83. How to find the most frequent value in an array?
`💡hint: np.bincount, argmax`

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
`💡hint: stride_tricks.as_strided`

#### 85. Create a 2D array subclass such that a[i,j] == a[j,i] (★★★)
`💡hint: class method`

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
`💡hint: np.tensordot`

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
`💡hint: np.add.reduceat`

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)
`💡hint: np.argsort | np.argpartition`

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
`💡hint: np.indices`

#### 91. How to create a record array from a regular array? (★★★)
`💡hint: np.core.records.fromarrays`

#### 92. Consider a large vector A, compute A to the power of 3 using 3 different methods (★★★)
`💡hint: np.power, *, np.einsum`

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
`💡hint: np.where`

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)
`💡hint: np.unpackbits`

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)
`💡hint: np.ascontiguousarray | np.unique`

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
`💡hint: np.einsum`

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
`💡hint: np.cumsum, np.interp`

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
`💡hint: np.logical_and.reduce, np.mod`

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
`💡hint: np.percentile`